apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    lp-service-id: hello-world-1
  name: hello-world-1
  namespace: default
data:
  nginx.conf: |
    worker_processes  auto;
    pid        /etc/nginx/nginx.pid;
    worker_rlimit_nofile 8192;

    events {}
    http {
      log_format combined_json '{ "@timestamp":"$time_iso8601",'
        '"remote_addr":"$remote_addr",'
        '"remote_user":"$remote_user",'
        '"scheme":"$scheme",'
        '"body_bytes_sent":"$body_bytes_sent",'
        '"bytes_sent":"$bytes_sent",'
        '"request_time":"$request_time",'
        '"status":$status,'
        '"request":"$request",'
        '"request_method":"$request_method",'
        '"request_length":"$request_length",'
        '"http_referrer":"$http_referer",'
        '"http_user_agent":"$http_user_agent"'
      '}';
      access_log  /dev/stdout combined_json;
      error_log  /dev/stdout warn;

      default_type application/octet-stream;

      server {
        listen       4000;

        location /api/health-check {
          default_type application/json;
          return 200 '{"status":"success"}';
        }

        location / {
          default_type application/text;
          return 200 'hello world 1';
        }
      }
    }
