apiVersion: v1
kind: Service
metadata:
  name: hello-world-1
  labels:
    lp-service-id: hello-world-1
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    lp-service-id: hello-world-1
  type: NodePort
